### ISSUE TITLE
Dflpy verbs return None type for name with the previous add_pipe

### ISSUE THREAD

**Issue by OscarDeGar** [zdelrosario/py_grama#111]
_Originally posted by @zdelrosario in https://github.com/zdelrosario/py_grama/pull/110#discussion_r655358998_

Dfply verbs return None Type when called by .format(fun.__name__) in the add_pipe function, so the previous method for documentation is invalid, hence it currently is only fun.__doc__.

**Comment by zdelrosario** [comment]
@OscarDeGar is this fixed with your recent PR?

**Comment by OscarDeGar** [comment]
This refers to:
![issue_111](https://user-images.githubusercontent.com/55853029/128374716-13d4e991-582d-43ab-a6bf-ed50f79597a4.png)
Currently the uncommented code does not work in tandem with the new class 'addName' for dfply verbs.

NOT SOLVED
